email:
  #Settings for the email account from which the emails will be send
  smtp: <your-email-server> #For example mail.domain.com
  port: <port> #537 for example
  account: <email-address> #Email account from which the emails will be send
  password: <password>
  myemail: <email-address> #Main email account where all the alerts will be sent
  test-mail:
    email-address: <email-address> #Email address where the test email will be sent

script-settings:
  check-time: 300 #Minimum check time needs to be set to 60 and needs to be whole number
  url-file: urls.txt #File name where the urls are stored (urls.txt is a default)
  timezone: utc #(default)
  send-alerts: true #(default)
  dev: yes #Show detailed description about the script operations 