email:
  smtp: mail.kristijan-projects.xyz
  port: 587
  account: alert@kristijan-projects.xyz
  password: .D,C{=MY7P(a<w;A
  myemail: work@kristijan.me #Main email account where all the alerts will be sent
  test-mail:
    email-address: work@kristijan.me #Email address where the test email will be sent

script-settings:
  check-time: 300 #Minimum check time needs to be set to 60 and needs to be whole number
  url-file: urls.txt #File name where the urls are stored (urls.txt is a default)
  timezone: utc #(default)
  send-alerts: true #(default)
  dev: yes #Show detailed description about the script operations 